name: Android CI #

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Cache debug keystore
      id: cache-debug-keystore
      uses: actions/cache@v4
      with:
        path: ~/.android/debug.keystore
        key: debug-keystore

    - name: Create debug keystore
      if: steps.cache-debug-keystore.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.android
        keytool -genkey -v -keystore ~/.android/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Sign APK
      id: sign_apk
      run: |
        $ANDROID_SDK_ROOT/build-tools/34.0.0/apksigner sign --ks ~/.android/debug.keystore --ks-pass pass:android --key-pass pass:android --ks-key-alias androiddebugkey app/build/outputs/apk/debug/app-debug.apk
        echo "signed_apk_path=app/build/outputs/apk/debug/app-debug.apk" >> $GITHUB_OUTPUT
      
    - name: Upload app-debug.apk
      uses: actions/upload-artifact@v4
      with:
        name: PrivateDNSAndroidTV
        path: ${{ steps.sign_apk.outputs.signed_apk_path }}
